### ISSUE TITLE
Build errors with MSVC /permissive- flag

### ISSUE THREAD

**Issue by xaltmiles** [ami-iit/matio-cpp#64]
**Issue:**

Library won't compile with MSVC if /permissive- flag is used.

**Proposed solution:**
Patch provided.

[0001-Allow-permissive-build-with-MSVC.patch](https://github.com/ami-iit/matio-cpp/files/10464540/0001-Allow-permissive-build-with-MSVC.patch)

**Comment by S-Dafarra** [comment]
Hi @xaltmiles, thanks for the issue and the suggestion. Feel free to open a PR with the suggested modifications!

**Comment by S-Dafarra** [comment]
I have opened https://github.com/ami-iit/matio-cpp/pull/65 to fix this
