### ISSUE TITLE
Problem with linking library

### ISSUE THREAD

**Issue by dptreurniet** [ami-iit/matio-cpp#66]
Hi,

For the last days I have been trying to link matio-cpp to my project, but without success. I am rather new to cmake, but it seems that I have successfully built and installed the binaries.
I included the library in my project with `find_package(matioCpp REQUIRED)` (which seems to find the package properly) and linking the libraries with `target_link_libraries(my_project PRIVATE matioCpp::matioCpp)`.

However, when trying to create a MAT-file, I get an `undefined reference` error for `matioCpp::File::Create(...)` and `matioCpp::File::~File()`, which indicates that only the headers are imported, but not the implementations. 

Any help would be greatly appreciated! I realize this is not really a problem that is specific to matio-cpp, but it would be awesome if someone could help me out a bit.

**Comment by traversaro** [comment]
Hello @dptreurniet !

Can you share something else about your project/how did you installd matio-cpp and the rest of dependencies? The use of `find_package` + `target_link_libraries` is quite standard (see for example https://github.com/robotology/robometry/blob/v1.2.0/src/examples/CMakeLists.txt), so I guess the problem is something specific to either your project or your setup. If you can't share your project, you can try to replicate the problem in a self-contained example that you can share (see https://stackoverflow.com/help/minimal-reproducible-example for more details). Furthermore, in general it is useful to have the **full error log**, not an extract of it, as you may be have noticed the `undefined reference`, but perhaps there was something else useful in the log that you did not noticed, and that someone with more experience could have noticed. 

Without this information, it is difficult for anyone helping you, as we do not have any information to process on your problem.

**Comment by dptreurniet** [comment]
Hi @traversaro!

Thanks for your reply :)

I started with HDF5, which was straight-forward using the .msi from their website (I am on running on Windows 11).

The following packages were built with the command `cmake --build . --target ALL_BUILD --config Release` (or `Debug`) and installed with `cmake --build . --target INSTALL--config Release`.

For zlib, this yielded the following files in C:\Program Files(x86)\zlib:
```
├───bin
│       zlib.dll
│       zlibd.dll
│
├───include
│       zconf.h
│       zlib.h
│
├───lib
│       zlib.lib
│       zlibd.lib
│       zlibstatic.lib
│       zlibstaticd.lib
│
└───share
    ├───man
    │   └───man3
    │           zlib.3
    │
    └───pkgconfig
            zlib.pc
```

Next step: matio. I built and installed again using cmake, using the just installed HDF5 and zlib include folder and release/debug libraries. That worked just fine, giving me the following in C:\Program Files(x86)\matio:
```
├───bin
│       libmatio.dll
│       matdump.exe
│
├───include
│       matio.h
│       matio_pubconf.h
│
└───lib
        libmatio.lib
```

Last step: matio-cpp. Again, built and installed using cmake, giving the following in C:\Program Files(x86)\matioCpp:
```
├───bin
│       matioCpp.dll
│       matioCppd.dll
│
├───CMake
│       matioCppConfig.cmake
│       matioCppConfigVersion.cmake
│       matioCppTargets-debug.cmake
│       matioCppTargets-release.cmake
│       matioCppTargets.cmake
│       visit_structConfig.cmake
│       visit_structConfigVersion.cmake
│       visit_structTargets.cmake
│
├───include
│   ├───matioCpp
│   │   │   CellArray.h
│   │   │   Config.h
│   │   │   ConversionUtilities.h
│   │   │   EigenConversions.h
│   │   │   Element.h
│   │   │   ExogenousConversions.h
│   │   │   File.h
│   │   │   ForwardDeclarations.h
│   │   │   matioCpp.h
│   │   │   MatvarHandler.h
│   │   │   MultiDimensionalArray.h
│   │   │   SharedMatvar.h
│   │   │   Span.h
│   │   │   Struct.h
│   │   │   StructArray.h
│   │   │   StructArrayElement.h
│   │   │   Variable.h
│   │   │   Vector.h
│   │   │   VectorIterator.h
│   │   │   WeakMatvar.h
│   │   │
│   │   └───impl
│   │           EigenConversions.tpp
│   │           Element.tpp
│   │           ExogenousConversionHelpers.tpp
│   │           ExogenousConversions.tpp
│   │           File.tpp
│   │           MultiDimensionalArray.tpp
│   │           StructArrayElement.tpp
│   │           Vector.tpp
│   │
│   └───visit_struct
│           visit_struct.hpp
│           visit_struct_boost_fusion.hpp
│           visit_struct_boost_hana.hpp
│           visit_struct_intrusive.hpp
│
├───lib
│       matioCpp.lib
│       matioCppd.lib
│
└───share
    └───matioCpp
        └───cmake
                FindMATIO.cmake
```

So, as far as I can tell, all packages were installed properly. The complete error is (with some file paths redacted):
```
:-1: error: ninja: build stopped: subcommand failed.
:-1: error: CMakeFiles/H2Analyst.dir/backend/dataset.cpp.obj: in function `H2A::Dataset::Dataset()':
C:\Users\...\dataset.cpp:7: error: undefined reference to `matioCpp::File::Create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, matioCpp::FileVersion, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
:-1: error: C:/Users/.../dataset.cpp:9: undefined reference to `matioCpp::File::~File()'
:-1: error: collect2.exe: error: ld returned 1 exit status
```

Hopefully this gives some insight towards a solution!
Cheers

**Comment by traversaro** [comment]
Which compiler are you using? MSVC or MinGW? Are you sure that you are using the same compiler for all the libraries, including the random binaries that you download from a website?  The C++ ABI between the two is different, so in general you can't mix libraries compiled with MSVC. 

General comment, perhaps a bit OT: if you need to compile more than a few C/C++ libraries, try to rely on a package manager (such as vcpkg, conan or conda with conda-forge). If you try to download random library binaries and manually compile libraries you always risk of getting problems like this one.

**Comment by dptreurniet** [comment]
I am using MSVC for all packages, but you could be right about the binaries for HDF5...
Regarding the package manager, matioCpp does not seem to be available. I just tried to install matio via vcpkg, which works fine. However, now I still have to manually build matioCpp right?

Not sure how to continue...

**Comment by traversaro** [comment]
> I am using MSVC for all packages, but you could be right about the binaries for HDF5...

Are you sure? The error message you are reporting is `:-1: error: collect2.exe: error: ld returned 1 exit status`, and the linker of GCC/MinGW is `ld`, while the one used by MSVC is `link`. 
If you share the `CMakeCache.txt` (or just the `CMAKE_CXX_COMPILER` value) of your project we can understand more.


> However, now I still have to manually build matioCpp right?

Yes, at the moment there is no matio-cpp port in vcpkg. However, using vcpkg at least you are able to be sure about the hdf5 and matio binaries you are using. To compile a CMake project against vcpkg dependencies, you just need to set in the CMake project the `CMAKE_TOOLCHAIN_FILE` to the one of vcpkg, see https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#cmake_toolchain_file .

**Comment by dptreurniet** [comment]
On second thought, you are totally correct. I am building a Qt application but I was using the MinGW version instead of the MSVC version. I changed that now. I have also added the` CMAKE_TOOLCHAIN_FILE` as you mentioned (this is done in the Qt Creator IDE).

The error I am now getting is that matio can not be found:
```
CMake Error at C:/Program Files (x86)/matioCpp/CMake/matioCppTargets.cmake:54 (set_target_properties):
  The link interface of target "matioCpp::matioCpp" contains:

    MATIO::MATIO

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/Program Files (x86)/matioCpp/CMake/matioCppConfig.cmake:32 (include)
  CMakeLists.txt:17 (find_package)
```

My CMakeLists.txt looks like this:
```
cmake_minimum_required(VERSION 3.5)

project(myProject VERSION 0.1 LANGUAGES CXX)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Widgets PrintSupport)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Widgets PrintSupport)

find_package(matioCpp REQUIRED)

set(PROJECT_SOURCES
        main.cpp

        backend/dataset.cpp
        backend/dataset.h

        ...
)

if(${QT_VERSION_MAJOR} GREATER_EQUAL 6)
    qt_add_executable(myProject 
        MANUAL_FINALIZATION
        resources.qrc
        ${PROJECT_SOURCES}
    )
# Define target properties for Android with Qt 6 as:
#    set_property(TARGET myProject APPEND PROPERTY QT_ANDROID_PACKAGE_SOURCE_DIR
#                 ${CMAKE_CURRENT_SOURCE_DIR}/android)
# For more information, see https://doc.qt.io/qt-6/qt-add-executable.html#target-creation
else()
    if(ANDROID)
        add_library(myProject SHARED
            ${PROJECT_SOURCES}
        )
# Define properties for Android with Qt 5 after find_package() calls as:
#    set(ANDROID_PACKAGE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/android")
    else()
        add_executable(myProject 
            ${PROJECT_SOURCES}
        )
    endif()
endif()

target_link_libraries(myProject PRIVATE Qt${QT_VERSION_MAJOR}::Widgets)
target_link_libraries(myProject PRIVATE Qt${QT_VERSION_MAJOR}::PrintSupport)
target_link_libraries(myProject PRIVATE matioCpp::matioCpp)

set_target_properties(myProject PROPERTIES
    MACOSX_BUNDLE_GUI_IDENTIFIER my.example.com
    MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
    MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
    MACOSX_BUNDLE TRUE
    WIN32_EXECUTABLE TRUE
)

install(TARGETS myProject 
    BUNDLE DESTINATION .
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}/extern/)

if(QT_VERSION_MAJOR EQUAL 6)
    qt_finalize_executable(myProject)
endif()
```

Thanks a lot for you help so far, I am learning a lot :)

**Comment by S-Dafarra** [comment]
Did you set the ``CMAKE_TOOLCHAIN_FILE`` also when compiling your project?

**Comment by dptreurniet** [comment]
I am compiling the project from within the Qt Creator IDE, which is where I added the tool chain indeed.

**Comment by S-Dafarra** [comment]
The weird thing is that the target ``MATIO::MATIO`` is created by the file ``findMATIO.cmake`` in ``share/matioCpp/cmake``. This file should be called by ``matioCppConfig.cmake``, that is called by ``find_package(matioCpp REQUIRED)``. Could you share the ``CMakeCache`` of your project? I would be interested in checking if ``MATIO_INCLUDE_DIR`` and ``MATIO_LIBRARY`` get properly set.

**Comment by dptreurniet** [comment]
I have attached the `CMakeCache` file:
[CMakeCache.txt](https://github.com/ami-iit/matio-cpp/files/11240262/CMakeCache.txt)

**Comment by traversaro** [comment]
I suspect something else could be installing a FindMATIO.cmake file that is shadowing the one installed by matio-cpp and is not defining the target we use.

**Comment by S-Dafarra** [comment]
A possible workaround could be:
- copy the [``findMATIO.cmake``](https://github.com/ami-iit/matio-cpp/blob/master/cmake/FindMATIO.cmake) file to a top-level folder named ``cmake`` in your project.
- Add the following lines before ``find_package(matioCpp REQUIRED)`` in your ``CMakeLists``
```cmake
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
find_package(MATIO REQUIRED)
```



> I suspect something else could be installing a FindMATIO.cmake file that is shadowing the one installed by matio-cpp and is not defining the target we use.

I was thinking the same. Not sure why these lines
```cmake
include(CMakeFindDependencyMacro)
set(CMAKE_MODULE_PATH_BK_matioCpp ${CMAKE_MODULE_PATH})
set(CMAKE_MODULE_PATH ${PACKAGE_PREFIX_DIR}/share/matioCpp/cmake)
find_package(MATIO)
find_package(visit_struct)
find_package(Eigen3)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH_BK_matioCpp})
```
where 
```cmake
PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE
```

in ``matioCppConfig.cmake`` are not working as expected.

@dptreurniet did you edit the installation files of ``matioCpp`` in any way?

**Comment by dptreurniet** [comment]
I'm very happy to say that copying another `findMatio.cmake` did the trick! My theory is that in my first attempts to build the packages, another `findMatio.cmake` was created and was still being used. Now I can hunt that down to clean the system up, but I am sure that I will manage with that. Thank you very much, @traversaro and @S-Dafarra for all the help and the quick responses. I am looking forward to created a nice application with this library now!
