### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by dptreurniet** [ami-iit/matio-cpp#69]
Hi,

When trying to run the example code of creating a file and writing some values to it, my program crashes with the following error:
![image](https://user-images.githubusercontent.com/18143971/232320388-8e63bd0d-a4c9-4b4b-9502-f05752f897a7.png)

When looking at the debug information, the error originates from the following line of code from the example:
`testString = "string content";`
Digging in further, the program crashes at the return statement of the `matioCpp::Vector<T> &matioCpp::Vector<T>::operator=(const string_input_type &other)` function that is called (line 213 in Vector.tpp).
When diving down deeper, functions are called from the `std::string` library and finally crashing at a call of `std::allocator<char>::deallocate`.

I am compiling this program using MSVC on Windows.
The code I am trying to get working:
```
    matioCpp::File file = matioCpp::File::Create("created_file.mat");

    matioCpp::String testString("string_name");
    testString = "string content";
    file.write(testString);
```

**Comment by S-Dafarra** [comment]
Hi @dptreurniet, the error is very weird. I am not able to reproduce it as currently the example works fine in CI, in Windows too (see https://github.com/ami-iit/matio-cpp/actions/runs/4708421328/jobs/8350849796)

I wonder if it could be related to some issue with the dependencies on your system.

**Comment by S-Dafarra** [comment]
Also, are you sure you are not running out of memory in your application?

**Comment by dptreurniet** [comment]
I decided to remove all packages and start over, so this issue is not present anymore.
