### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by S-Dafarra** [ami-iit/matio-cpp#73]
Tests are failing on Windows with `conda` dependencies with the errors like
``
Error starting read events: socket is not connected
``

See https://github.com/ami-iit/matio-cpp/actions/runs/6032215717

The weird thing is that it happens for all the tests, also those related to `visit_struct`

**Comment by traversaro** [comment]
Related comment: https://github.com/conda-forge/cmake-feedstock/pull/189#issuecomment-1700526117 .

**Comment by S-Dafarra** [comment]
Thanks @traversaro. https://github.com/conda-forge/cmake-feedstock/pull/190 fixed the issue. Closing
